server.port=8083
spring.application.name=meme-service

spring.datasource.url=jdbc:h2:mem:memedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update

# Endereços dos outros serviços
user-service.url=http://localhost:8081
category-service.url=http://localhost:8082

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
